In [15]:
import pandas as pd

# Load the dataset
file_path = r'C:\Users\sudee\OneDrive\Documents\Newyork Citi Bike Project\02 Data\Original Data\citibike.csv'
df = pd.read_csv(file_path)

# Display the first few rows of the dataset
print(df.head())

# Basic data cleaning
# Remove duplicates
df = df.drop_duplicates()

# Check for missing values
missing_values = df.isnull().sum()
print("Missing values per column:\n", missing_values)

# Optionally, drop rows with missing values or handle them appropriately
df = df.dropna()  # Dropping rows with missing values (if applicable)

# Convert any necessary columns to the correct data type (e.g., dates)
# Assuming 'starttime' and 'stoptime' are datetime fields
df['start_time'] = pd.to_datetime(df['start_time'])
df['end_time'] = pd.to_datetime(df['end_time'])

# Display cleaned data information
print(df.info())

# Save the cleaned data (optional)
df.to_csv(r'C:\Users\sudee\OneDrive\Documents\Newyork Citi Bike Project\02 Data\prepared Data\cleaned_citibike.csv', index=False)

  trip_id  bike_id weekday  start_hour           start_time  start_station_id  \
0  LnQzQk    16013     Mon          18  2013-09-09 18:18:55               523
1  IL9boN    15230     Thu          18  2013-09-12 18:38:53               257
2  46clGB    17942     Wed          19  2013-09-18 19:44:04               479
3  v7vdFt    19683     Sat          11  2013-09-28 11:54:37               527
4  VGBsb5    18024     Sat          18  2013-09-07 18:08:22               521

        start_station_name  start_station_latitude  start_station_longitude  \
0          W 38 St & 8 Ave               40.754666               -73.991382
1  Lispenard St & Broadway               40.719392               -74.002472
2          9 Ave & W 45 St               40.760193               -73.991255
3          E 33 St & 1 Ave               40.743156               -73.974347
4          8 Ave & W 31 St               40.750450               -73.994811

              end_time  end_station_id     end_station_name  \
0  2013-09-09 18:35:28             334      W 20 St & 7 Ave
1  2013-09-12 18:48:34             236  St Marks Pl & 2 Ave
2  2013-09-18 19:50:05             513     W 56 St & 10 Ave
3  2013-09-28 12:03:58             441      E 52 St & 2 Ave
4  2013-09-07 18:46:38             476      E 31 St & 3 Ave

   end_station_latitude  end_station_longitude  trip_duration      subscriber  \
0             40.742388             -73.997262            993      Subscriber
1             40.728419             -73.987140            581      Subscriber
2             40.768254             -73.988639            361      Subscriber
3             40.756014             -73.967416            561      Subscriber
4             40.743943             -73.979661           2296  Non-Subscriber

   birth_year  gender
0      1968.0       2
1      1983.0       1
2      1989.0       1
3      1988.0       2
4         NaN       0
Missing values per column:
 trip_id                       0
bike_id                       0
weekday                       0
start_hour                    0
start_time                    0
start_station_id              0
start_station_name            0
start_station_latitude        0
start_station_longitude       0
end_time                      0
end_station_id                0
end_station_name              0
end_station_latitude          0
end_station_longitude         0
trip_duration                 0
subscriber                    0
birth_year                 6979
gender                        0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 43021 entries, 0 to 49999
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   trip_id                  43021 non-null  object
 1   bike_id                  43021 non-null  int64
 2   weekday                  43021 non-null  object
 3   start_hour               43021 non-null  int64
 4   start_time               43021 non-null  datetime64[ns]
 5   start_station_id         43021 non-null  int64
 6   start_station_name       43021 non-null  object
 7   start_station_latitude   43021 non-null  float64
 8   start_station_longitude  43021 non-null  float64
 9   end_time                 43021 non-null  datetime64[ns]
 10  end_station_id           43021 non-null  int64
 11  end_station_name         43021 non-null  object
 12  end_station_latitude     43021 non-null  float64
 13  end_station_longitude    43021 non-null  float64
 14  trip_duration            43021 non-null  int64
 15  subscriber               43021 non-null  object
 16  birth_year               43021 non-null  float64
 17  gender                   43021 non-null  int64
dtypes: datetime64[ns](2), float64(5), int64(6), object(5)
memory usage: 6.2+ MB
None

In [31]:
# Descriptive statistics for continuous variables
descriptive_stats = df.describe()
print("Descriptive Statistics for Continuous Variables:")
print(descriptive_stats)

# Frequency counts for categorical variables
categorical_columns = ['weekday', 'subscriber', 'gender']  # Assuming these are categorical columns in your data
for col in categorical_columns:
    print(f"\nValue counts for {col}:\n", df[col].value_counts())

Descriptive Statistics for Continuous Variables:
            bike_id    start_hour                     start_time  \
count  43021.000000  43021.000000                          43021
mean   17618.307966     14.084563  2013-09-16 18:03:18.214453504
min    14556.000000      0.000000            2013-09-01 00:00:35
25%    16188.000000     10.000000            2013-09-09 17:18:25
50%    17590.000000     15.000000            2013-09-17 06:36:35
75%    19028.000000     18.000000            2013-09-24 07:38:11
max    20642.000000     23.000000            2013-09-30 23:58:17
std     1676.892609      4.932676                            NaN

       start_station_id  start_station_latitude  start_station_longitude  \
count      43021.000000            43021.000000             43021.000000
mean         437.226610               40.734477               -73.990952
min           72.000000               40.680342               -74.017134
25%          304.000000               40.721101               -74.000040
50%          402.000000               40.736245               -73.990765
75%          485.000000               40.749718               -73.981948
max         3002.000000               40.770513               -73.950048
std          340.831639                0.019598                 0.012370

                            end_time  end_station_id  end_station_latitude  \
count                          43021     43021.00000          43021.000000
mean   2013-09-16 18:16:51.640593920       434.59815             40.734069
min              2013-09-01 00:07:15        72.00000             40.680342
25%              2013-09-09 17:34:46       305.00000             40.720828
50%              2013-09-17 06:42:06       402.00000             40.735877
75%              2013-09-24 07:51:15       483.00000             40.749013
max              2013-10-01 00:15:29      3002.00000             40.770513
std                              NaN       332.88413              0.019602

       end_station_longitude  trip_duration    birth_year        gender
count           43021.000000    43021.00000  43021.000000  43021.000000
mean              -73.991245      770.62337   1975.627786      1.247693
min               -74.017134       60.00000   1899.000000      0.000000
25%               -74.000271      395.00000   1968.000000      1.000000
50%               -73.990985      621.00000   1978.000000      1.000000
75%               -73.982578      999.00000   1984.000000      1.000000
max               -73.950048     2697.00000   1997.000000      2.000000
std                 0.012375      523.46211     11.089001      0.431785

Value counts for weekday:
 weekday
Mon    6800
Fri    6596
Wed    6494
Tue    6433
Thu    6222
Sun    5510
Sat    4966
Name: count, dtype: int64

Value counts for subscriber:
 subscriber
Subscriber    43021
Name: count, dtype: int64

Value counts for gender:
 gender
1    32361
2    10658
0        2
Name: count, dtype: int64


1. What are the busiest bike stations in New York City?
2. How does bike usage vary by time of day or day of the week?
3. Is there a relationship between trip duration and the distance between start and end stations?
4. How does bike usage differ by user type (e.g., subscribers vs. casual users)?
5. What is the distribution of bike usage across different age groups?
6. Is there a noticeable trend in bike usage based on the user's gender?